import { ApplicationConfig, provideZonelessChangeDetection, importProvidersFrom } from '@angular/core';
import { provideRouter } from '@angular/router';
import { routes } from './app.routes';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { authInterceptor } from './core/infrastructure/auth.interceptor';
import {
  LucideAngularModule,
  LogIn,
  User,
  ArrowRight,
  ShoppingCart,
  Settings,
  LogOut,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  Receipt,
  X,
  Delete,
  Plus,
  Minus,
  Trash2,
  ShoppingBag,
  Utensils,
  Star,
  Coins,
  DollarSign,
  AlertCircle,
  Printer,
  Check,
  ArrowUpRight,
  Save,
  Edit2,
  LineChart,
  Package,
  CalendarRange,
  ArrowLeft,
  LayoutDashboard,
  ShieldCheck,
  Calendar,
  QrCode,
  FileText,
  Lock,
  Activity,
  TrendingUp,
  History,
  AlertTriangle,
  CreditCard,
  Sparkles,
  Layers,
  RotateCcw,
  Search,
  CupSoda,
  Eye,
  EyeOff,
  Bluetooth
} from 'lucide-angular';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZonelessChangeDetection(),
    provideRouter(routes),
    provideHttpClient(withInterceptors([authInterceptor])),
    importProvidersFrom(
      LucideAngularModule.pick({
        LogIn,
        User,
        ArrowRight,
        ShoppingCart,
        Settings,
        LogOut,
        ChevronLeft,
        ChevronRight,
        ChevronUp,
        ChevronDown,
        Receipt,
        X,
        Delete,
        Plus,
        Minus,
        Trash2,
        ShoppingBag,
        Utensils,
        Star,
        Coins,
        DollarSign,
        AlertCircle,
        Printer,
        Check,
        ArrowUpRight,
        Save,
        Edit2,
        LineChart,
        Package,
        CalendarRange,
        ArrowLeft,
        LayoutDashboard,
        ShieldCheck,
        Calendar,
        QrCode,
        FileText,
        Lock,
        Activity,
        TrendingUp,
        History,
        AlertTriangle,
        CreditCard,
        Sparkles,
        Layers,
        RotateCcw,
        Search,
        CupSoda,
        Eye,
        EyeOff,
        Bluetooth
      })
    )
  ]
};



// Trigger rebuild 2